lst2=["apple","banana","carrat","dremstick","egg","fish","epic","fruits","grapes","hunger","icecream"]
lst2.append("juice")
print(lst2)
lst3=["mango","orange","papaya"]
lst2.extend(lst3)
print(lst2)
lst2.insert(2,"gvava")
print(lst2)
lst2.remove("gvava")
print(lst2)
print(lst2.pop(5))

print(lst2.count("apple"))
lst2.sort()
lst2.sort(reverse=True)
print(lst2)
lst4=lst2.copy()
lst4=lst3.copy()
print(lst4)