import  math as m
print(m.sqrt(16))
print(m.sqrt(25))
print(m.floor(3.9))
print(m.ceil(2.1))
print(m.pow(2,3))
print(m.pi)
print(m.e)
print(m.sqrt(25))
print(m.factorial(5))
print(m.gcd(3,5))
print(m.lcm(4,8))
print(m.comb(2,1))
print(m.perm(5,2))
print(m.isqrt(25))
# rounding and represenatation function 
print(m.ceil(3.2))
print(m.floor(3.2))
print(m.trunc(3.2))
print(m.fabs(-3,-2))
print(m.copysign(-3,-2))
print(m.fmod(5,2))
print(m.remainder(5,2))
print(m.modf(3.2,2.1))
print(m.frexp(16))
print(m.ldxp(2,3))